### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by ohri-anurag**

### CODE REVIEW

**Review by Tristano8 — APPROVED** [review]
No nix updates? Oh it's not in the template - we should probably fix that.

Can you run `nix flake update --commit-lock-file` and check that you can enter a nix shell by running `nix develop`?

**Comment by ohri-anurag** [comment]
> nix flake update --commit-lock-file

It is building ghc-9.6.3. Should it be doing that?

**Comment by Tristano8** [comment]
The `flake.nix` file has this:

```
compiler-nix-name = "ghc963";
```

So it's doing what it's supposed to. Whether that's the right compiler to choose is another question - i think most of our other open source repos use 9.2. @JackKelly-Bellroy any reason for this to change?

**Comment by ohri-anurag** [comment]
> The `flake.nix` file has this:
> 
> ```
> compiler-nix-name = "ghc963";
> ```
> 
> So it's doing what it's supposed to. Whether that's the right compiler to choose is another question - i think most of our other open source repos use 9.2. @JackKelly-Bellroy any reason for this to change?

No, I meant should it be building the compiler instead of downloading it from somewhere?

**Comment by JackKelly-Bellroy** [comment]
No, it shouldn't. This repo should use whatever the default compiler is for the haskell.nix checkout in the flake.nix, to have the best cache hit rate.

**Comment by Tristano8** [comment]
This seems fine so i'm going to merge in @ohri-anurag 's stead

**Pull request merged**
